# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ld-devenv"

  config.vm.hostname = "ld-devenv"

  config.vm.define "ld-devenv" do |ld_devenv|
  end

  #config.vm.synced_folder "C:\\_src\\Shared", "/home/vagrant/Shared"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ld-devenv"
    vb.memory = 6100
    vb.cpus = 2
    vb.gui = true
  end

end